ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - name: Run dev server
    init: |
      npm install
      gp sync-done install
    command: npm run dev
  - name: Show outdated packages
    init: gp sync-await install
    command: npm outdated
    openMode: split-right

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - svelte.svelte-vscode
