ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - svelte.svelte-vscode
